import Head from "next/head";
import Table from "./Table/index";
import TableDate from "../models/tableDate";
import Student from "../models/student";
import classes from "./index.module.css";
import Table2 from "./components/Table2/Table2";

const DATE = new TableDate(2021, "Oktober");
const STUDENT_1 = new Student(
  "Bartolomey",
  [1, 4, 8, 13, 16, 22, 25, 30],
  2,
  5
);

export default function Home() {
  const students: Student[] = [STUDENT_1, STUDENT_1, STUDENT_1, STUDENT_1];

  return (
    <div>
      <Head>
        <title>Performance Student Journal</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
          crossOrigin="anonymous"
        ></link>
        <link rel="icon" href="/favicon.jpg" />
      </Head>

      <main className={classes.main}>
        <Table data={DATE} students={students} />
      </main>

      {/* <section className={classes.table2}>
        <Table2 />
      </section> */}

      <footer></footer>
    </div>
  );
}
